RESULT = min-caml
CC = gcc
CFLAGS = -g -O2 -Wall

default: native-code
	rm *.cmx
	rm *.cmi
	rm *.o

clean:: nobackup

# mliファイルなどなかった
SOURCES = \
float.c global.ml type.ml id.ml m.ml\
s.ml time.ml syntax.ml parser.mly lexer.mll\
typing.ml kNormal.ml alpha.ml beta.ml betaTuple.ml\
assoc.ml inline.ml elim.ml constArray.ml cse.ml\
constFold.ml globalEnv.ml closure.ml asm.ml virtual.ml\
sglobal.ml simm.ml block.ml liveness.ml coloring.ml\
toAsm.ml regAlloc.ml regAllocWithColoring.ml output.ml emit.ml\
main.ml

include OCamlMakefile
